# Generated by Django 3.1.3 on 2021-05-06 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='company',
        ),
    ]
