# Generated by Django 3.1.3 on 2021-05-06 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
    ]
