# Generated by Django 3.1.3 on 2021-05-03 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0002_auto_20210503_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quize',
            name='compony_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp', to='test_api.compony'),
        ),
    ]
