# Generated by Django 3.1.3 on 2021-05-06 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0002_auto_20210506_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_name',
            name='company_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='test_api.company'),
        ),
    ]
