# Generated by Django 3.1.3 on 2021-05-03 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0003_auto_20210503_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='save_test',
            name='test_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testscore', to='test_api.test_name'),
        ),
    ]
