# Generated by Django 3.1.3 on 2021-05-07 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0003_auto_20210506_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_name',
            name='company_name',
        ),
        migrations.AddField(
            model_name='test_name',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='company', to='test_api.company'),
        ),
    ]
