# Generated by Django 3.1.3 on 2021-05-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0004_auto_20210507_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_name',
            name='company',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
