# Generated by Django 3.1.3 on 2021-05-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0004_auto_20210503_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='save_test',
            name='test_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
