# Generated by Django 3.1.3 on 2021-05-04 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0005_auto_20210503_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='save_test',
            name='compony_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
