# Generated by Django 3.1.3 on 2021-05-04 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0006_save_test_compony_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compony',
            new_name='Company',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='compony_name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='quize',
            old_name='compony_name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='save_test',
            old_name='compony_name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='test_name',
            old_name='compony',
            new_name='company',
        ),
    ]
