# Generated by Django 3.1.3 on 2021-05-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0007_auto_20210504_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='Company_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='Tagline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
