# Generated by Django 3.1.3 on 2021-05-05 05:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0008_auto_20210505_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=50, null=True),
        ),
    ]
